apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bar-file-pvc
  namespace: ace-app-example
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ocs-storagecluster-ceph-rbd
  resources:
    requests:
      storage: 1Gi
