apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-bar
spec:
  workspaces:
    - name: source
  steps:
  - name: clean-directories
    image: apalumbo925/acetektonpipeline_example:latest
    script: |
      #!/bin/sh
      rm -r ~/runTimeFiles/*
      rm -r ~/buildBar/*
  - name: build-bar
    image: apalumbo925/acetektonpipeline_example:latest
    script: |
      #!/bin/sh
      shopt -s extglob
      shopt -s nullglob
      current_time=$(date "+%Y.%m.%d-%H.%M.%S")
      mkdir -p ~/runTimeFiles
      mkdir -p ~/buildBar
      cd ~/runTimeFiles
      for dir  in !(*olicy*); do
          ( cd "$dir" && zip -r ~/buildBar/"${dir%/}".appzip . )
      done
      cp -r *olicy* ~/buildBar
      cd ~/buildBar
      zip -rm "$current_time".bar .
