apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: create-ace-config
spec:
  resources:
    inputs:
    - name: workspace
      type: git
  steps:
  - name: create-config
    image: apalumbo925/acetektonpipeline_example:latest
    command:
      - bash
      - -c
      - |
        cat << EOF > /workspace/integrationserver.yaml
        apiVersion: appconnect.ibm.com/v1beta1
        kind: IntegrationServer
        metadata:
          name: ace-server-example
          namespace: ace_app_example
        spec:
          designerFlowsOperationMode: disabled
          createDashboardUsers: true
          license:
            accept: true
            license: L-APEH-CJUCNR
            use: CloudPakForIntegrationNonProduction
          pod:
            containers:
              runtime:
                resources:
                  limits:
                    cpu: 500m
                    memory: 512Mi
                  requests:
                    cpu: 500m
                    memory: 512Mi
          replicas: 1
          router:
            timeout: 120s
          service:
            endpointType: http
          useCommonServices: true
          version: 12.0.8.0
          adminServerSecure: true
          configurations:
          - ace-config
        EOF
