apiVersion: v1
kind: Pod
metadata:
  name: temporary-pod
  namespace: ace-app-example
spec:
  volumes:
    - name: bar-volume
      persistentVolumeClaim:
        claimName: bar-file-pvc
  containers:
    - name: temporary-container
      image: busybox
      command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5; done"]
      volumeMounts:
        - name: bar-volume
          mountPath: /data
